name: docker

on:
  release:
    types: [published]

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Publish version env var
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push the image
        run: |
          docker buildx build . \
            --build-arg BUILD_ID=${{ github.run_id }} \
            --build-arg COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA") \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.VERSION }} \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest \
            --platform linux/amd64,linux/arm64 \
            --push

      - name: Push readme
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          target: fontebasso/php-nginx
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme: README.md
